name: Ubuntu Qt 6 C/C++ CI

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: git init
      run: git submodule update --init --remote libbitdht/ libretroshare/ openpgpsdk/ retroshare-webui/ && git --no-pager log --max-count 1
    - name: git submodule supportlibs
      run: git submodule update --init supportlibs/librnp supportlibs/restbed #supportlibs/rapidjson
    - name: run apt update
      run: sudo apt-get update
    - name: apt install
      run: sudo apt-get install g++ cmake qt6-base-dev qt6-multimedia-dev libasio-dev libbz2-dev libjson-c-dev libssl-dev libsqlcipher-dev libupnp-dev libxss-dev rapidjson-dev libbotan-2-dev doxygen qt6-5compat-dev libqt6core5compat6-dev libsecret-1-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev libavcodec-dev
    - name: print working directory
      run: pwd && ls -la
    - name: qmake
      run: |
        qmake6 CONFIG+=debug \
        CONFIG+=rs_autologin \
        CONFIG+=rs_webui \
        CONFIG+=rs_jsonapi \
        CONFIG+=wikipoos \
        CONFIG+=gxsthewire \
        CONFIG+=retroshare_plugins
    - name: make
      run: make
    - name: make check
      run: make check
